### ISSUE TITLE
autopublish.templates option not working

### ISSUE THREAD

**Issue by DavidUnzue** [groenewege/kirby-auto-publish#1]
The default behaviour of the plugin is working: if no options are set within the config.php, all new pages are being published by default.

But after I set the `autopublish.templates` option with any of my blueprints names, auto publishing isn't working anymore.

**Comment by groenewege** [comment]
Hi,

I just tested the plugin on a clean install and everything seems to work.

Here are the steps I took : 
- download the Kirby 2.1 starter kit : http://getkirby.com/try
- copy the `autopublish` directory into the `site/plugins` directory
- add the configuration `c::set('autopublish.templates', array('project'));` to the `site/config/config.php` file
- when creating a new page from the root of the Admin Panel (using the 'Page' template) the new page is not auto published 
- when creating a new page in the 'Projects' section of the Admin Panel (using the 'Project' template) the new page is auto published

Maybe this will help you find out why the plugin does not work on your project.
If you can't find the cause of the problem, you can send me a copy of your code base and I will take a look.

best regards,
gunther

**Comment by DavidUnzue** [comment]
Okay, I don't know why, but everything is working know :-)
