### ISSUE TITLE
Turn off at config level for certain environments

### ISSUE THREAD

**Issue by jklue** [groenewege/kirby-auto-publish#4]
I love this plugin. Can I make it only work on my local and dev environments, but turn it completely off in the live/production config file?

**Comment by groenewege** [comment]
If you want to disable in production, the easiest solution is to not deploy the directory of this plugin to production. If you want to set a different configuration in development and production, check out [this article](https://getkirby.com/blog/multi-environment-setup)

**Comment by jklue** [comment]
Thank you @groenewege. I did end up removing the directory from the entire project. I couldn't get a line in my production config file to prevent it from auto saving. I tried this: `c::set('autopublish.templates', array(''));` but it continued to auto publish everything.
